#!/usr/bin/env bash
# This script temporarily modifies the /etc/hosts file localhost and facebook.com
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts